[package]
name = "haptic-toolbox"
version = "0.1.0"
authors = ["bold <bold@cryptoguru.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.26.1"
num-traits = "0.2.11"